vich_uploader:
    db_driver: orm
    
    mappings:
        images_product:
            uri_prefix: '/hello/%app.path.images_product%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.images_product%'
            delete_on_remove: true
            delete_on_update: true